#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Port-Sight BETA Installer
# Downloads docker-compose.beta.yml, generates .env, and starts
# the beta application via Docker Compose.
#
# This installs alongside production without interfering — uses
# separate ports (8080/8443), separate database, separate config.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/install-beta.sh | bash
#   # or
#   bash install-beta.sh
# ─────────────────────────────────────────────────────────────

DEFAULT_DIR="/opt/port-sight-beta"
COMPOSE_URL="https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/docker-compose.beta.yml"

echo ""
echo "  ┌──────────────────────────────────┐"
echo "  │    Port-Sight BETA Installer     │"
echo "  └──────────────────────────────────┘"
echo ""
echo "  This installs the beta channel alongside any existing"
echo "  production install. It uses separate ports and a separate"
echo "  database — your production data is not affected."
echo ""

# ── Pre-flight checks ──────────────────────────────────────
command -v docker >/dev/null 2>&1 || {
  echo "Error: Docker is not installed."
  echo "  Install Docker: https://docs.docker.com/engine/install/"
  echo "  Quick install on Linux: curl -fsSL https://get.docker.com | sudo sh"
  exit 1
}
docker compose version >/dev/null 2>&1 || docker-compose version >/dev/null 2>&1 || {
  echo "Error: Docker Compose is not installed."
  echo "  It's included with Docker Engine 20.10+ and Docker Desktop."
  echo "  See: https://docs.docker.com/compose/install/"
  exit 1
}

# ── Install directory prompt ──────────────────────────────
if [ -n "${PORT_SIGHT_DIR:-}" ]; then
  INSTALL_DIR="$PORT_SIGHT_DIR"
else
  echo "  Where should Port-Sight Beta be installed?"
  echo "  This should be DIFFERENT from your production install directory."
  echo ""
  echo "  The default is $DEFAULT_DIR. Just press Enter to accept."
  echo ""
  printf "  Install directory [%s]: " "$DEFAULT_DIR"
  read -r INPUT_DIR < /dev/tty
  INSTALL_DIR="${INPUT_DIR:-$DEFAULT_DIR}"
fi

# ── Create install directory ───────────────────────────────
echo ""
echo "Install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR/certs"
cd "$INSTALL_DIR"

# ── Download docker-compose.beta.yml ───────────────────────
echo "Downloading docker-compose.beta.yml..."
curl -fsSL "$COMPOSE_URL" -o docker-compose.yml

# ── Generate .env if it doesn't exist ──────────────────────
if [ -f .env ]; then
  echo "Existing .env found — keeping current configuration."
else
  echo "Generating .env with secure random secrets..."
  echo ""

  # HTTP port
  echo "  What port should Port-Sight Beta listen on?"
  echo "  The default is 8080 to avoid conflicting with production on port 80."
  echo ""
  printf "  HTTP port [8080]: "
  read -r INPUT_PORT < /dev/tty
  HTTP_PORT="${INPUT_PORT:-8080}"

  # Server address(es) (for CORS)
  echo ""
  echo "  How will users access Port-Sight Beta in their browser?"
  echo "  Enter the server's IP address, hostname, or domain name."
  echo ""
  printf "  Server address(es) [localhost]: "
  read -r INPUT_ADDR < /dev/tty
  INPUT_ADDR="${INPUT_ADDR:-localhost}"

  # Build CORS origins
  CORS_VALUE=""
  IFS=',' read -ra ADDRS <<< "$INPUT_ADDR"
  for addr in "${ADDRS[@]}"; do
    addr="$(echo "$addr" | xargs)"
    if [ -z "$addr" ]; then continue; fi
    if [ "$HTTP_PORT" = "80" ]; then
      origin="http://${addr}"
    else
      origin="http://${addr}:${HTTP_PORT}"
    fi
    if [ -z "$CORS_VALUE" ]; then
      CORS_VALUE="$origin"
    else
      CORS_VALUE="${CORS_VALUE},${origin}"
    fi
  done

  echo ""

  # Generate secrets
  SECRET_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  if command -v python3 >/dev/null 2>&1; then
    FERNET_KEY=$(python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
  else
    FERNET_KEY=$(openssl rand -base64 32 | tr '+/' '-_')
  fi

  cat > .env << EOF
# ── Port-Sight BETA Configuration ────────────────────────
# Generated by install-beta.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# This is the BETA channel — separate from production.
# To change settings, edit this file and restart:
#   cd $INSTALL_DIR && docker compose up -d

# ── Network ───────────────────────────────────────────────
HTTP_PORT=${HTTP_PORT}
# HTTPS_PORT=8443
CORS_ORIGINS=${CORS_VALUE}

# ── Database ──────────────────────────────────────────────
POSTGRES_USER=portsight
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=portsight

# ── Security Secrets ──────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
CREDENTIAL_ENCRYPTION_KEY=${FERNET_KEY}

# ── Authentication ────────────────────────────────────────
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=480

# ── Display Options ───────────────────────────────────────
STRIP_SWITCH_DOMAIN=false

# ── Scheduled Polling ─────────────────────────────────────
POLL_SCHEDULE_HOUR=2
POLL_SCHEDULE_MINUTE=0

# ── Version Pinning ───────────────────────────────────────
# PORT_SIGHT_VERSION=2.0.0-beta.1
EOF

  echo ".env created with auto-generated secrets."
fi

# ── Pull images and start ─────────────────────────────────
echo ""
echo "Pulling Docker images (beta channel)..."
docker compose pull

echo ""
echo "Starting Port-Sight Beta..."
docker compose up -d

echo ""
echo "  ✓ Port-Sight BETA is running!"
echo ""
APP_URL=$(grep '^CORS_ORIGINS=' .env 2>/dev/null | cut -d= -f2- || echo "http://localhost:8080")
echo "  Open ${APP_URL} in your browser to complete setup."
echo "  (This is a separate instance from production with its own database.)"
echo ""
echo "  Useful commands:"
echo "    cd $INSTALL_DIR"
echo "    docker compose logs -f        # View logs"
echo "    docker compose down            # Stop"
echo "    docker compose pull && docker compose up -d  # Update"
echo ""
echo "  NOTE: This is the BETA channel. Features here are experimental"
echo "  and may change. Do not use for production workloads."
echo ""
