#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Port-Sight Installer
# Downloads docker-compose.prod.yml, generates .env, and starts
# the application via Docker Compose.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/install.sh | bash
#   # or
#   bash install.sh
# ─────────────────────────────────────────────────────────────

DEFAULT_DIR="/opt/port-sight"
COMPOSE_URL="https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/docker-compose.prod.yml"
ENV_EXAMPLE_URL="https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/.env.example"

echo ""
echo "  ┌──────────────────────────────────┐"
echo "  │       Port-Sight Installer       │"
echo "  └──────────────────────────────────┘"
echo ""

# ── Pre-flight checks ──────────────────────────────────────
command -v docker >/dev/null 2>&1 || {
  echo "Error: Docker is not installed."
  echo "  Install Docker: https://docs.docker.com/engine/install/"
  echo "  Quick install on Linux: curl -fsSL https://get.docker.com | sudo sh"
  exit 1
}
docker compose version >/dev/null 2>&1 || docker-compose version >/dev/null 2>&1 || {
  echo "Error: Docker Compose is not installed."
  echo "  It's included with Docker Engine 20.10+ and Docker Desktop."
  echo "  See: https://docs.docker.com/compose/install/"
  exit 1
}

# ── Install directory prompt ──────────────────────────────
# Allow override via environment variable, otherwise prompt
if [ -n "${PORT_SIGHT_DIR:-}" ]; then
  INSTALL_DIR="$PORT_SIGHT_DIR"
else
  echo "  Where should Port-Sight be installed?"
  echo "  This folder will contain the configuration files (docker-compose.yml,"
  echo "  .env, and certificates). The application itself runs inside Docker."
  echo ""
  echo "  The default is $DEFAULT_DIR. Just press Enter to accept."
  echo ""
  printf "  Install directory [%s]: " "$DEFAULT_DIR"
  read -r INPUT_DIR < /dev/tty
  INSTALL_DIR="${INPUT_DIR:-$DEFAULT_DIR}"
fi

# ── Create install directory ───────────────────────────────
echo ""
echo "Install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR/certs"
cd "$INSTALL_DIR"

# ── Download docker-compose.prod.yml ───────────────────────
echo "Downloading docker-compose.prod.yml..."
curl -fsSL "$COMPOSE_URL" -o docker-compose.yml

# ── Generate .env if it doesn't exist ──────────────────────
if [ -f .env ]; then
  echo "Existing .env found — keeping current configuration."
else
  echo "Generating .env with secure random secrets..."
  echo ""

  # ── Interactive prompts ──────────────────────────────────
  # Read from /dev/tty so prompts work even when piped (curl | bash)

  # HTTP port
  echo "  What port should Port-Sight listen on?"
  echo "  The default is 80 (standard web traffic). Just press Enter to use 80."
  echo ""
  echo "  TIP: If you plan to use HTTPS instead, just use port 80 for now."
  echo "  You can enable HTTPS after installation by placing certificate files"
  echo "  in the certs/ folder. See the deployment guide for details."
  echo ""
  printf "  HTTP port [80]: "
  read -r INPUT_PORT < /dev/tty
  HTTP_PORT="${INPUT_PORT:-80}"

  # Server address(es) (for CORS)
  echo ""
  echo "  How will users access Port-Sight in their browser?"
  echo "  Enter the server's IP address, hostname, or domain name."
  echo ""
  echo "  If users will access it from multiple addresses (for example,"
  echo "  both localhost AND a network IP), separate them with commas."
  echo ""
  echo "  Examples:"
  echo "    192.168.1.50                        (single IP)"
  echo "    portsight.company.com               (domain name)"
  echo "    localhost, 192.168.1.50             (multiple addresses)"
  echo ""
  printf "  Server address(es) [localhost]: "
  read -r INPUT_ADDR < /dev/tty
  INPUT_ADDR="${INPUT_ADDR:-localhost}"

  # Build CORS origins from the inputs (supports comma-separated addresses)
  CORS_VALUE=""
  IFS=',' read -ra ADDRS <<< "$INPUT_ADDR"
  for addr in "${ADDRS[@]}"; do
    addr="$(echo "$addr" | xargs)"   # trim whitespace
    if [ -z "$addr" ]; then continue; fi
    if [ "$HTTP_PORT" = "80" ]; then
      origin="http://${addr}"
    else
      origin="http://${addr}:${HTTP_PORT}"
    fi
    if [ -z "$CORS_VALUE" ]; then
      CORS_VALUE="$origin"
    else
      CORS_VALUE="${CORS_VALUE},${origin}"
    fi
  done

  echo ""

  # Generate secrets
  SECRET_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  # Generate Fernet key (base64-encoded 32 bytes)
  if command -v python3 >/dev/null 2>&1; then
    FERNET_KEY=$(python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
  else
    FERNET_KEY=$(openssl rand -base64 32 | tr '+/' '-_')
  fi

  cat > .env << EOF
# ── Port-Sight Configuration ─────────────────────────────
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# To change these settings later, edit this file and restart:
#   cd $INSTALL_DIR && docker compose up -d

# ── Network ───────────────────────────────────────────────
# HTTP_PORT: The port number Port-Sight listens on.
#   Default is 80 (standard web port). Change this if port 80
#   is already used by another application on this server.
HTTP_PORT=${HTTP_PORT}

# HTTPS_PORT: Uncomment to enable HTTPS on a specific port.
#   You also need to place cert.pem and key.pem in the certs/ folder.
# HTTPS_PORT=443

# CORS_ORIGINS: The full URL that users type in their browser
#   to access Port-Sight. This MUST match exactly, including the
#   port number (if not 80). If this is wrong, the app will load
#   but show errors when trying to fetch data.
#   Examples: http://192.168.1.50  http://10.0.0.5:3000
#             https://portsight.company.com
CORS_ORIGINS=${CORS_VALUE}

# ── Database ──────────────────────────────────────────────
# These control the built-in PostgreSQL database container.
# You do NOT need an external database — one is included.
# Do not change these after first run unless you recreate the database.
POSTGRES_USER=portsight
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=portsight

# ── Security Secrets ──────────────────────────────────────
# Auto-generated. Do not share these or commit them to version control.
# SECRET_KEY: Used to sign authentication tokens (login sessions).
# CREDENTIAL_ENCRYPTION_KEY: Used to encrypt stored SNMP passwords.
SECRET_KEY=${SECRET_KEY}
CREDENTIAL_ENCRYPTION_KEY=${FERNET_KEY}

# ── Authentication ────────────────────────────────────────
# How long a user stays logged in before needing to log in again.
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=480

# ── Display Options ───────────────────────────────────────
# STRIP_SWITCH_DOMAIN: If your switches have names like "sw1.corp.com",
#   set to true to display just "sw1" in the UI.
STRIP_SWITCH_DOMAIN=false

# ── Scheduled Polling ─────────────────────────────────────
# Port-Sight can automatically poll all switches on a daily schedule.
# Set the time of day (24-hour format, server timezone).
# Default: 2:00 AM. Configure additional schedules in the web UI.
POLL_SCHEDULE_HOUR=2
POLL_SCHEDULE_MINUTE=0

# ── Version Pinning ───────────────────────────────────────
# By default, Port-Sight uses the latest version. Uncomment and set
# a version number to lock to a specific release.
# PORT_SIGHT_VERSION=1.3.0
EOF

  echo ".env created with auto-generated secrets."
fi

# ── Pull images and start ─────────────────────────────────
echo ""
echo "Pulling Docker images..."
docker compose pull

echo ""
echo "Starting Port-Sight..."
docker compose up -d

echo ""
echo "  ✓ Port-Sight is running!"
echo ""
# Read the CORS value back from .env to show the correct URL
APP_URL=$(grep '^CORS_ORIGINS=' .env 2>/dev/null | cut -d= -f2- || echo "http://localhost")
echo "  Open ${APP_URL} in your browser to complete setup."
echo "  (First visit will prompt you to create an admin account.)"
echo ""
echo "  Useful commands:"
echo "    cd $INSTALL_DIR"
echo "    docker compose logs -f        # View logs"
echo "    docker compose down            # Stop"
echo "    docker compose pull && docker compose up -d  # Update"
echo ""
echo "  For HTTPS, place your cert.pem and key.pem in:"
echo "    $INSTALL_DIR/certs/"
echo "  Then restart: docker compose restart frontend"
echo ""
