#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Port-Sight Installer
# Downloads docker-compose.prod.yml, generates .env, and starts
# the application via Docker Compose.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/install.sh | bash
#   # or
#   bash install.sh
# ─────────────────────────────────────────────────────────────

INSTALL_DIR="${PORT_SIGHT_DIR:-$HOME/port-sight}"
COMPOSE_URL="https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/docker-compose.prod.yml"
ENV_EXAMPLE_URL="https://raw.githubusercontent.com/shunsing22/port-sight-releases/main/.env.example"

echo ""
echo "  ┌──────────────────────────────────┐"
echo "  │       Port-Sight Installer       │"
echo "  └──────────────────────────────────┘"
echo ""

# ── Pre-flight checks ──────────────────────────────────────
command -v docker >/dev/null 2>&1 || {
  echo "Error: Docker is not installed."
  echo "  Install Docker: https://docs.docker.com/engine/install/"
  echo "  Quick install on Linux: curl -fsSL https://get.docker.com | sudo sh"
  exit 1
}
docker compose version >/dev/null 2>&1 || docker-compose version >/dev/null 2>&1 || {
  echo "Error: Docker Compose is not installed."
  echo "  It's included with Docker Engine 20.10+ and Docker Desktop."
  echo "  See: https://docs.docker.com/compose/install/"
  exit 1
}

# ── Create install directory ───────────────────────────────
echo "Install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR/certs"
cd "$INSTALL_DIR"

# ── Download docker-compose.prod.yml ───────────────────────
echo "Downloading docker-compose.prod.yml..."
curl -fsSL "$COMPOSE_URL" -o docker-compose.yml

# ── Generate .env if it doesn't exist ──────────────────────
if [ -f .env ]; then
  echo "Existing .env found — keeping current configuration."
else
  echo "Generating .env with secure random secrets..."

  # Generate secrets
  SECRET_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  # Generate Fernet key (base64-encoded 32 bytes)
  if command -v python3 >/dev/null 2>&1; then
    FERNET_KEY=$(python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
  else
    FERNET_KEY=$(openssl rand -base64 32 | tr '+/' '-_')
  fi

  cat > .env << EOF
# ── Port-Sight Configuration ─────────────────────────────
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Ports (change if 80/443 are already in use)
HTTP_PORT=80
# HTTPS_PORT=443

# PostgreSQL
POSTGRES_USER=portsight
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=portsight

# Backend secrets (auto-generated — do not share)
SECRET_KEY=${SECRET_KEY}
CREDENTIAL_ENCRYPTION_KEY=${FERNET_KEY}

# Auth
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# CORS — set to the URL users will access Port-Sight from
# Examples: http://192.168.1.50  or  https://portsight.company.com
CORS_ORIGINS=http://localhost

# Switch name formatting
STRIP_SWITCH_DOMAIN=false

# Scheduled poll time (24h, server timezone)
POLL_SCHEDULE_HOUR=2
POLL_SCHEDULE_MINUTE=0

# Pin a specific version (default: latest)
# PORT_SIGHT_VERSION=1.3.0
EOF

  echo ".env created with auto-generated secrets."
fi

# ── Pull images and start ─────────────────────────────────
echo ""
echo "Pulling Docker images..."
docker compose pull

echo ""
echo "Starting Port-Sight..."
docker compose up -d

echo ""
echo "  ✓ Port-Sight is running!"
echo ""
echo "  Open http://localhost in your browser to complete setup."
echo "  (First visit will prompt you to create an admin account.)"
echo ""
echo "  Useful commands:"
echo "    cd $INSTALL_DIR"
echo "    docker compose logs -f        # View logs"
echo "    docker compose down            # Stop"
echo "    docker compose pull && docker compose up -d  # Update"
echo ""
echo "  For HTTPS, place your cert.pem and key.pem in:"
echo "    $INSTALL_DIR/certs/"
echo "  Then restart: docker compose restart frontend"
echo ""
